# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sm_BgNs_EE0uoB5AAN8sESAsw7y_Tipv
"""

soma = 0
for i in range (100):
  soma = i + soma

soma