# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svGXiDQsYVzhLICTo20O7dEMMossX65-
"""

for i in range(1,201):
  if i%2==0:
    print(i)