# -*- coding: utf-8 -*-
"""projeto2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9zaJ5KbYwn_jacWtLOcTlEW1KXzC0RY
"""

numeros = []
par = []
impar = []

for numero in range(0,20):
  numeros.append(int(input("Digite um numero: ")))

for numero in range (0,20):
  if numeros[numero] % 2 == 0 :
    par.append(numeros[numero])
  else:
    impar.append(numeros[numero])

print("Vetor com 20 elementos: " + str(numeros))
print("Vetor com numeros pares: " + str(par))
print("Vetor com numeros impares: " + str(impar)
)