# -*- coding: utf-8 -*-
"""pareseimpares.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OiIwdzUoK3WB-oobSTH-Fpe-fxtHBadl
"""

inteiros = []
pares = []
impares = []

for i in range(0,20):
    numero = int(input("Digite um inteiro: "))
    inteiros.append(numero)
    if numero % 2 == 0:
        pares.append(numero)
    else:
        impares.append(numero)


print("\nInteiros")
for numero in inteiros:
    print(f"{numero}", end=" ")

print("\nPares")
for numero in pares:
    print(f"{numero}", end=" ")

print("\nImpares")
for numero in impares:
    print(f"{numero}", end=" ")