# -*- coding: utf-8 -*-
"""pares200.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZWa9Z4TZ5dSBttPFm3MzF-wY4qsPSur
"""

for i in range (1,201):
  if i%2==0:
    print([i])