# -*- coding: utf-8 -*-
"""soma100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msyCM7h5VcKayYrvosLHl125xwiKt_4K
"""

soma = 0
for i in range (100):
  soma = i + soma

soma









